### ISSUE TITLE
Latest device pack (1.3.0) in uvision fails to compile cmsis_device_g0/Source/Templates/system_stm32g0xx.c

### ISSUE THREAD

**Issue by davidklopsteins** [STMicroelectronics/cmsis_device_g0#1]
The file **cmsis_device_g0/Source/Templates/system_stm32g0xx.c** does not compile due to #define's missing in
**cmsis_device_g0/Include/stm32g030xx.h**

The #defines that were in the device pack 1.2.0 that have been removed in 1.3.0 and are causing the failure are;

#define RCC_CFGR_SWS_HSI               (0UL)                                   /*!< HSI used as system clock */
#define RCC_CFGR_SWS_HSE               (0x00000008UL)                          /*!< HSE used as system clock */
#define RCC_CFGR_SWS_PLL               (0x00000010UL)                          /*!< PLL used as system clock */
#define RCC_CFGR_SWS_LSI               (0x00000018UL)                          /*!< LSI used as system clock */
#define RCC_CFGR_SWS_LSE               (0x00000020UL) 

Please note I have not checked the other STM32G0 family header files. These need to be checked to

**Comment by ASELSTM** [comment]
Hi @davidklopsteins,

First we would like to thank you for your contribution.

Actually, these defines has been removed from all STM32G0 CMSIS header files and redefined in the [RCC HAL driver](https://github.com/STMicroelectronics/STM32CubeG0/blob/5cb06333a6a43cefbe145f10a5aa98d3cc4cffee/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_rcc.h#L566-L570) as they are not specific to the CMSIS but rather to the HAL/LL drivers.

To solve this issue, two possibilities are suggested : 

1.  You can include the header file of the RCC HAL module[ stm32g0xx_hal_rcc.h](https://github.com/STMicroelectronics/STM32CubeG0/blob/master/Drivers/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal_rcc.h)  to your project.

2. You can replace theses constants by their corresponding bit definition combinations within your application code.  They could then be replaced as following : 

```
RCC_SYSCLKSOURCE_HSI            could be replaced by        0x00000000U
RCC_SYSCLKSOURCE_HSE            could be replaced by        RCC_CFGR_SW_0
RCC_SYSCLKSOURCE_PLLCLK         could be replaced by        RCC_CFGR_SW_1
RCC_SYSCLKSOURCE_LSI            could be replaced by        (RCC_CFGR_SW_1 | RCC_CFGR_SW_0) 
RCC_SYSCLKSOURCE_LSE            could be replaced by        RCC_CFGR_SW_2 

```

Hope that will help you.

with regards,

**Comment by ASELSTM** [comment]
Hi @davidklopsteins,

Please allow me to close this thread. You can reopen it at any time if you have details to provide us to help you.

Thank you for your comprehension and thank you once more for your contribution

With regards,
