### ISSUE TITLE
Incorrect README.md title 

### ISSUE THREAD

**Issue by glegrain** [STMicroelectronics/cmsis_device_g0#2]
The README.md title mentions "STM32CubeU5". Should it not say "STM32CubeG0" instead ?

**Comment by RKOUSTM** [comment]
Hi @glegrain,

Thank you for  your contribution. The issue you pointed out has been confirmed. An update will be made available in GitHub as soon as possible.

Thank you once again for your contribution. We are looking forward to reading from you again.

With regards,
