### ISSUE TITLE
Disjunct names RCC_CFGR_SWS_HSISYS vs RCC_CFGR_SWS_HSI and  RCC_CFGR_SWS_PLLRCLK vs RCC_CFGR_SWS_PLL

### ISSUE THREAD

**Issue by UweBonnes** [STMicroelectronics/cmsis_device_g0#5]
the headers use RCC_CFGR_SWS_HSISYS and  RCC_CFGR_SWS_PLLRCLK  while all other families use RCC_CFGR_SWS_HSI  and 
RCC_CFGR_SWS_PLL. This is unneeded complication.

**Comment by TOUNSTM** [comment]
Hello @UweBonnes,

The naming convention you mentioned (RCC_CFGR_SWS_HSISYS and RCC_CFGR_SWS_PLLRCLK) comes directly from the reference manual. To ensure consistency and accuracy, we align our headers with the terminology used in the reference manual.

![image](https://github.com/user-attachments/assets/dbb43209-b6a7-47c4-bc45-aa8e90c84c54)

Please allow me to close this issue. thank you for your understanding.

Best regards,
